fn main() {
    try {
        let a: i32 = 10
        let b: i32 = 0
        let c = a / b
        print(c)
    } catch err {
        print("Error caught: {}", err)
    }
}
